openapi: 3.0.0
info:
  title: Combined App API
  version: 1.0.0
  description: API for User Management, Authenticated ToDo, and Blog system
servers:
  - url: http://localhost:3000
paths:
  /api/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created

  /api/login:
    post:
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: JWT token

  /api/me:
    get:
      summary: Get current logged-in user info
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile

  /api/users/{id}:
    put:
      summary: Update user info
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: Updated user
    delete:
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted

  /api/todos:
    get:
      summary: Get current user's todos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of todos
    post:
      summary: Create todo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                dueDate:
                  type: string
                completed:
                  type: boolean
      responses:
        "201":
          description: Todo created

  /api/todos/{id}:
    get:
      summary: Get todo by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Todo item
    put:
      summary: Update todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                dueDate:
                  type: string
                completed:
                  type: boolean
      responses:
        "200":
          description: Updated
    delete:
      summary: Delete todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted

  /api/posts:
    get:
      summary: Get all public posts
      responses:
        "200":
          description: Post list
    post:
      summary: Create new post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: Created

  /api/posts/{id}:
    get:
      summary: Get post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Post item
    put:
      summary: Update post
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Updated
    delete:
      summary: Delete post
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
